set(RUNTIME_LAYERS_PROJECT_NAME RNGOEngine_Rumtime_Layers)
add_library(${RUNTIME_LAYERS_PROJECT_NAME} STATIC
)
target_include_directories(${RUNTIME_LAYERS_PROJECT_NAME} PUBLIC include)
target_link_libraries(${RUNTIME_LAYERS_PROJECT_NAME} PUBLIC ${LAYER_PROJECT_NAME})
target_link_libraries(${RUNTIME_LAYERS_PROJECT_NAME} PUBLIC ${PROFILING_PROJECT_NAME} ${UTILITIES_PROJECT_NAME})
